<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>

</body>

<script>
  // 面试够用版

  function myPromise(constructor) {
    let self = this;
    self.status = "pending" //定义状态改变前的初始状态
    self.value = undefined; //定义状态为 resolved 的时候的状态
    self.reason = undefined; //定义状态为 rejected 的时候的状态
    function resolve(value) {
      //两个==="pending"，保证了状态的改变是不可逆的
      if (self.status === "pending") {
        self.value = value;
        self.status = "resolved";
      }
    }

    function reject(reason) {
      //两个==="pending"，保证了状态的改变是不可逆的
      if (self.status === "pending") {
        self.reason = reason;
        self.status = "rejected";
      }
    }
    //捕获构造异常
    try {
      constructor(resolve, reject);
    } catch (e) {
      reject(e);
    }
  }
  // 同时，需要在 myPromise 的原型上定义链式调用的 then 方法：
  myPromise.prototype.then = function (onFullfilled, onRejected) {
    let self = this;
    switch (self.status) {
      case "resolved":
        onFullfilled(self.value);
        break;
      case "rejected":
        onRejected(self.reason);
        break;
      default:
    }
  }
  // 复制代码测试一下：
  var p = new myPromise(function (resolve, reject) {
    resolve(1)
  });
  p.then(function (x) {
    console.log(x)
  })
  //输出 1

  // ##大厂专供版

  const PENDING = "pending";
  const FULFILLED = "fulfilled";
  const REJECTED = "rejected";

  function Promise(excutor) {
    let that = this; // 缓存当前 promise 实例对象
    that.status = PENDING; // 初始状态
    that.value = undefined; // fulfilled 状态时 返回的信息
    that.reason = undefined; // rejected 状态时 拒绝的原因
    that.onFulfilledCallbacks = []; // 存储 fulfilled 状态对应的 onFulfilled 函数
    that.onRejectedCallbacks = []; // 存储 rejected 状态对应的 onRejected 函数

    function resolve(value) { // value成功态时接收的终值
      if (value instanceof Promise) {
        return value.then(resolve, reject);
      }
      // 实践中要确保 onFulfilled 和 onRejected 方法异步执行，且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行。
      setTimeout(() => {
        // 调用resolve 回调对应onFulfilled函数
        if (that.status === PENDING) {
          // 只能由pending状态 => fulfilled状态 (避免调用多次resolve reject)
          that.status = FULFILLED;
          that.value = value;
          that.onFulfilledCallbacks.forEach(cb => cb(that.value));
        }
      });
    }

    function reject(reason) { // reason失败态时接收的拒因
      setTimeout(() => {
        // 调用reject 回调对应onRejected函数
        if (that.status === PENDING) {
          // 只能由pending状态 => rejected状态 (避免调用多次resolve reject)
          that.status = REJECTED;
          that.reason = reason;
          that.onRejectedCallbacks.forEach(cb => cb(that.reason));
        }
      });
    }

    // 捕获在excutor执行器中抛出的异常
    // new Promise((resolve, reject) => {
    //     throw new Error('error in excutor')
    // })
    try {
      excutor(resolve, reject);
    } catch (e) {
      reject(e);
    }

  }

  Promise.prototype.then = function (onFulfilled, onRejected) {
    const that = this;
    let newPromise;
    // 处理参数默认值 保证参数后续能够继续执行
    onFulfilled =
      typeof onFulfilled === "function" ? onFulfilled : value => value;
    onRejected =
      typeof onRejected === "function" ? onRejected : reason => {
        throw reason;
      };
    if (that.status === FULFILLED) { // 成功态
      return newPromise = new Promise((resolve, reject) => {
        setTimeout(() => {
          try {
            let x = onFulfilled(that.value);
            resolvePromise(newPromise, x, resolve, reject); // 新的 promise resolve 上一个 onFulfilled 的返回值
          } catch (e) {
            reject(e); // 捕获前面 onFulfilled 中抛出的异常 then(onFulfilled, onRejected);
          }
        });
      })
    }

    if (that.status === REJECTED) { // 失败态
      return newPromise = new Promise((resolve, reject) => {
        setTimeout(() => {
          try {
            let x = onRejected(that.reason);
            resolvePromise(newPromise, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        });
      });
    }

    if (that.status === PENDING) { // 等待态
      // 当异步调用resolve/rejected时 将onFulfilled/onRejected收集暂存到集合中
      return newPromise = new Promise((resolve, reject) => {
        that.onFulfilledCallbacks.push((value) => {
          try {
            let x = onFulfilled(value);
            resolvePromise(newPromise, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        });
        that.onRejectedCallbacks.push((reason) => {
          try {
            let x = onRejected(reason);
            resolvePromise(newPromise, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        });
      });
    }

  };
</script>

</html>